### ISSUE TITLE
Customize checkbox in header

### ISSUE THREAD

**Issue by Priyantha-Kingslake** [maxim-saplin/data_table_2#227]
Allow customization on how the checkboxes will be displayed in DataTable2. 

Ability to remove the checkbox in the header (select all checkbox) when showCheckboxColumn is set to true

**Comment by jbournonville** [comment]
Hello, I've created a PR to solve this : https://github.com/maxim-saplin/data_table_2/pull/270

@Priyantha-Kingslake if you want to try it on your project, update your dependencies like so :
```yaml
  data_table_2:
    git:
      url: https://github.com/jbournonville/data_table_2
```
